name: Xcode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      matrix:
        run-config:
          - { scheme: 'Fakery-iOS', destination: 'platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro' }
          - { scheme: 'Fakery-macOS', destination: 'platform=macOS' }

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p

    - name: Show Build Settings
      run: xcodebuild -project Fakery.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -project Fakery.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

    - name: Show Available Destinations
      run: xcodebuild -project Fakery.xcodeproj -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

    - name: build and test
      run: xcodebuild clean test -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary
